name: Build

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.sys.os }}
    runs-on: ${{ matrix.sys.os }}
    strategy:
      fail-fast: true
      matrix:
        sys:
          - { os: windows-2019, shell: bash }
          - { os: ubuntu-20.04, shell: bash }
          - { os: macos-11, shell: bash }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_ENVIRONMENT_MACOS: CC=clang CXX=clang++
          CIBW_ENVIRONMENT_WINDOWS: CC=gcc.exe CXX=g++.exe

      - uses: actions/upload-artifact@v3
        with:
          name: python-wheels
          path: ./wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: python-wheels
          path: dist

      - name: Publish package
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_KEY }}

      - name: Publish package
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}
